apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-order-processing:t6.2
          env:
            - name: Services__QuoteManagement
              value: http://ecommerceddd-quote-management-api
            - name: Services__PaymentProcessing
              value: http://ecommerceddd-payment-processing-api
            - name: Services__ShipmentProcessing
              value: http://ecommerceddd-shipment-processing-api
            - name: Services__SignalRClient
              value: http://ecommerceddd-signalr-api
            - name: KafkaConsumer__Group
              value: OrderProcessing-Group
            - name: KafkaConsumer__Topics__0
              value: payments
            - name: KafkaConsumer__Topics__1
              value: shipments
            - name: KafkaConsumer__Topics__2
              value: orders
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: order-processing
  ConnectionStrings__DefaultConnection: Host=postgres.platform.svc.cluster.local;Port=5432;Database=ordersdb;Username=postgres;Password=postgres
