apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-inventory-management:main-latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: inventory-management
