apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecom-dev

resources:
- common/env-config.yaml
- services/customer-management
- services/product-catalog
- services/inventory-management
- services/quote-management
- services/order-processing
- services/payment-processing
- services/shipment-processing
- services/identityserver
- services/apigateway
- services/signalr
- services/spa
- ingress/apigateway-ingress.yaml
- ingress/identityserver-ingress.yaml
- ingress/signalr-ingress.yaml
- ingress/spa-ingress.yaml

images:
- name: ghcr.io/just-vile/ecommerceddd-apigateway
  newTag: cn.2
- name: ghcr.io/just-vile/ecommerceddd-customer-management
  newName: ghcr.io/just-vile/ecommerceddd-customer-management
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-identityserver
  newTag: cn.2
- name: ghcr.io/just-vile/ecommerceddd-inventory-management
  newName: ghcr.io/just-vile/ecommerceddd-inventory-management
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-order-processing
  newName: ghcr.io/just-vile/ecommerceddd-order-processing
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-payment-processing
  newName: ghcr.io/just-vile/ecommerceddd-payment-processing
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-product-catalog
  newName: ghcr.io/just-vile/ecommerceddd-product-catalog
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-quote-management
  newName: ghcr.io/just-vile/ecommerceddd-quote-management
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-shipment-processing
  newName: ghcr.io/just-vile/ecommerceddd-shipment-processing
  newTag: sha-a60442b
- name: ghcr.io/just-vile/ecommerceddd-signalr
  newTag: cn.2
- name: ghcr.io/just-vile/ecommerceddd-spa
  newName: ghcr.io/just-vile/ecommerceddd-spa
  newTag: sha-a60442b

commonAnnotations:
  ecommerceddd.io/gitops-sha: $Format:%H$

patches:
- path: common/image-pull-secret-patch.yaml
  target:
    kind: Deployment
