apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  template:
    spec:
      containers:
        - name: spa
          image: ghcr.io/just-vile/ecommerceddd-spa:t6
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spa-config
data:
  config.json: |
    {
      "apiBaseUrl": "http://api.dev.ecommerceddd.local",
      "identityUrl": "http://id.dev.ecommerceddd.local",
      "signalRHubUrl": "http://hub.dev.ecommerceddd.local"
    }
