apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/dotnet-service

namePrefix: ecommerceddd-apigateway-

commonLabels:
  app.kubernetes.io/name: ecommerceddd-apigateway
  app.kubernetes.io/instance: apigateway

patchesStrategicMerge:
  - patch.yaml
