apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-apigateway:t6.2
          env:
            - name: Cors__AllowedOrigins__0
              value: http://app.dev.ecommerceddd.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: apigateway
