apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-customer-management:main-latest
          env:
            - name: Services__IdentityServer
              value: http://ecommerceddd-identityserver-api
            - name: TokenIssuerSettings__Authority
              value: http://ecommerceddd-identityserver-api
            - name: TokenIssuerSettings__ClientId
              value: ecommerceddd.application_client
            - name: TokenIssuerSettings__ClientSecret
              value: secret33587^&%&^%&^f3%%%
            - name: TokenIssuerSettings__Scope
              value: ecommerceddd-api.scope read write
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: customer-management
  ConnectionStrings__DefaultConnection: Host=postgres.platform.svc.cluster.local;Port=5432;Database=customersdb;Username=postgres;Password=postgres
 
 