apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/dotnet-service

namePrefix: ecommerceddd-shipment-processing-

commonLabels:
  app.kubernetes.io/name: ecommerceddd-shipment-processing
  app.kubernetes.io/instance: shipment-processing

patchesStrategicMerge:
  - patch.yaml
