apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-shipment-processing:t6
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: shipment-processing
  ConnectionStrings__DefaultConnection: Host=postgres.platform.svc.cluster.local;Port=5432;Database=shipmentsdb;Username=postgres;Password=P@55w0rd
