apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-shipment-processing:t7.1
          env:
            - name: TokenIssuerSettings__Scope
              value: ecommerceddd-api.scope read write delete
            - name: DebeziumSettings__ConnectorUrl
              value: http://connect.platform.svc.cluster.local:8083/connectors/shipments-connector
            - name: DebeziumSettings__DatabaseName
              value: shipmentsdb
            - name: DebeziumSettings__TopicPrefix
              value: shipments
            - name: DebeziumSettings__TransformsTopicReplacement
              value: shipments
            - name: DebeziumSettings__SlotName
              value: shipments
            - name: DebeziumSettings__SchemaIncludeList
              value: public
            - name: DebeziumSettings__TableIncludeList
              value: public.mt_doc_outboxmessages
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: shipment-processing
  ConnectionStrings__DefaultConnection: Host=postgres.platform.svc.cluster.local;Port=5432;Database=shipmentsdb;Username=postgres;Password=postgres
