apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: platform
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: broker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
