apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/dotnet-service

namePrefix: ecommerceddd-identityserver-

commonLabels:
  app.kubernetes.io/name: ecommerceddd-identityserver
  app.kubernetes.io/instance: identityserver

patchesStrategicMerge:
  - patch.yaml
