apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/just-vile/ecommerceddd-payment-processing:cn.2
          env:
            - name: Services__InventoryManagement
              value: http://ecommerceddd-inventory-management-api
            - name: Services__CustomerManagement
              value: http://ecommerceddd-customer-management-api
            - name: DebeziumSettings__ConnectorUrl
              value: http://connect.platform.svc.cluster.local:8083/connectors/payments-connector
            - name: DebeziumSettings__DatabaseName
              value: paymentsdb
            - name: DebeziumSettings__TopicPrefix
              value: payments
            - name: DebeziumSettings__TransformsTopicReplacement
              value: payments
            - name: DebeziumSettings__SlotName
              value: payments
            - name: DebeziumSettings__SchemaIncludeList
              value: public
            - name: DebeziumSettings__TableIncludeList
              value: public.mt_doc_outboxmessages
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Service__Name: payment-processing
  ConnectionStrings__DefaultConnection: Host=postgres.platform.svc.cluster.local;Port=5432;Database=paymentsdb;Username=postgres;Password=postgres
