apiVersion: v1
kind: Service
metadata:
  name: spa
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spa
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
